require "rake/testtask"
require "rake/clean"

ROOT = "lib/cgi/htmlentities"

CLEAN.include("doc")
DOCTYPES = %w[html4 xhtml1]
DATA_FILES = DOCTYPES.map{ |d| "#{ROOT}/lib/htmlentities/mappings/#{d}.rb" }
SOURCES = FileList["lib/src/htmlentities/**/*.rb"] - DATA_FILES

task :default => [:entities, :test]

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/cgi/htmlentities/test_*.rb']
  t.ruby_opts << "-w"
  t.verbose = true
end

DOCTYPES.each do |name|
  file "#{ROOT}/lib/htmlentities/mappings/#{name}.rb" do |f|
    sh %{ruby #{ROOT}/util/build_entities.rb #{name} > #{f.name}}
  end
end

file "doc" => SOURCES do |f|
  sh %{rdoc #{SOURCES.join(' ')}}
end

task :entities => DATA_FILES

desc "Run benchmark"
task :benchmark do |t|
  system "ruby -v"
  system "ruby #{ROOT}/perf/benchmark.rb"
end

desc "Use profiler to analyse encoding and decoding"
task :profile do |t|
  system "ruby -v"
  system "ruby #{ROOT}/perf/profile.rb"
end
